Theoretical Questions:

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?


Purpose:
*  Numpy means Numerical Python.
*  It offers powerful features for
   working with multi dimension arrays and performing various mathematical operational efficiently.
* It is a fundamental library for
  scientific computing.
* It is an open-source Python library that has a wide-range of inbuilt functions.

Advantages:

* It is a capable  of handling amounts of homogeneous data
* It also provides high-level syntax for a wide range of numerical operations.
** Pythons ability to handle decimal numbers enables exact arithmetic operations, which are particularly helpful in financial applications where precision is essential.  
** Python's decimal module helps prevent rounding errors to floating point intergers and allows arbitory precision arithmetic.





2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean():It is a function used to calculate arithmetic mean of given array along with the given axis.
* All the elements have equal weight.
* Weight cannot be passed through the parameter of the given function.
Syntax: np.mean(arr,axis=None)

np.avaerage():The arithmatic mean and weighted average calculations are more flexible with np.average()
* All the elements may and may not have equal weights.
* Weights can be passed through the parameter of the given function.
Syntax:numpy.average(arr,axis=None,Weights=None)

-->Both np.mean() and np.average() does the same job of calculating mean/average, the only difference comes when we are calculating the weighted average.
In this case we use np.average() than np.mean()

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

Numpy's np.flip() allows to flip or reverse the contents of an array along an axis.Numpys reverse the contents of all axis of input array if we don't specify the axis.
for 1-D array


In [34]:
arr=np.array([1,2,3,4,5,6,7,8])
reversed_arr=np.flip(arr)
print('Reversed Array:',reversed_arr)

Reversed Array: [8 7 6 5 4 3 2 1]


In [40]:
arr=np.array([[1,2,3],[5,6,7]])
reversed_arr=np.flip(arr)
print(reversed_arr)

[[7 6 5]
 [3 2 1]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Numerical data types: the 5 basic numerical types represnting booleans(bool),intergers(int),unsignes integers(int),floating point(float), and complex.


*  Basic numerical type name combined with a numeric bitsize defines a concrete type.the bitwise is the number of bits that are neede to represent a single va;lue in memory.For example numpy.float64 is a 64-bit floating point data type.

Data type of string and Bytes:Numpy supports storing unicode strings the numpy.str_ dtype(u character code),null-terminated byte(numpy.bytes_)(s character code), and arbitary byte numpy.void(v character code).These are fixed -width data types.They are parameterized by a width, in either byets or unicode points, thatr are  a single data element in the array must fit inside.This means that storing an array of buyte sequences or strings using this data type requires calculating the sizes of the largest test or byte sequence



5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarrays:N-Dimensional array in Numpy.
An array class in numpy is called as ndarray.
It is a multidimensional container of items of the sametype and size.
The contents of an ndarray can be accesed and modified of dimensions of the array is defined by its shape.
ndarray in NumPy is array in memory stores a homogenous data.
Python list is a heterogeneous lists.The main difference is list can store multiple data types at one time.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Performance benefits:NumPy array are optimized for numerical computations, with effecient element-wise operations and mathematical functions.The operations resolting in fastre performance than equivalent operations in lists.
Python's NumPy library supports optimizes numerical array and matrix operations.

Python's lists: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python's interpretation overhead.They are generally used as general-purpose data structures.
* A list is a built-in data structures that can hold elements of varying data types. The flexibility of lists comes at the cost of memory efficiency.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

vstack():The function is used to stack the sequence of input arrays vertically to make 2 single arrays.

Syntax:numpy.vstack(tup)
Parameters:
tup:Tuple containing arrays to be stacked.The arrays must have the same shape along all but the first axis.

Return:The Stacked array of the input arrays.

In [41]:
in_arr1 = np.array([ 1, 2, 3])
print("1st Input array : \n", in_arr1)
in_arr2 = np.array([ 4, 5, 6])
print("2nd Input array : \n", in_arr2)
out_arr = np.vstack((in_arr1, in_arr2))
print("Output vertically stacked array:\n", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
 [[1 2 3]
 [4 5 6]]


hstack():numpy.hstack() function is u=sed to stack the sequemnce of input arrays horizontally to make a single array.

Syntax:numpy.hstack(tup)

Parameters:
tup:Tuple containing arrays to be stacked.The arrays must have the same shape along all the second axis.
Return: The stacked array of the input arrays.

In [42]:
in_arr1 = np.array([ 1, 2, 3])
print("1st Input array : \n", in_arr1)
in_arr2 = np.array([ 4, 5, 6])
print("2nd Input array : \n", in_arr2)
out_arr = np.hstack((in_arr1, in_arr2))
print("Output horizontally stacked array:\n", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
 [1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

numpy.fliplr(m):It reverse the order of elements along with axis_1(left/right)
For a 2-D array this flips of the entries in each row in the left/right direction columns are preserveds but appear in a different order than before.

Parameter:
m:array_like
input array,must be atleast 2-D

Returns :f:ndarray a view of m with the columns reversed.Since a view is returned, this operation is O(1).

numpy.flipud(m):It is a reverse order of elements along axis 0 (up/down)

for a 2-D  array, this flips thed entries in each column in the up/down direction.Rows are preserved, but appear in a different order than befpore.

Parameters:m:array_like
input array

Returns:pout: array_like
A view of m with the rows reserved.Since a view is returned,this operation is O(1).

9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

numpy.array_split() method, we can get the splitted array of yhaving different dimensions by using numpy.array_split() method.

Syntax:numpy.array_split()

Return:return the splitted array of one dimensions.
array_split() splitting into equal or nearly equal sub-arrays or similar to numpy.Split(),but it allows for uneven splitting of arrays.This is useful when the array cannot be evenly divided by the specified number of splits.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization : It enables the use of efficient pre-compliled functions and mathematical operations on nump[y arrays and adata sequences.Vertorization is a method of performing array operations without the use of loops.

Broadcasting:It is a powerful featuer in NumPy that allows performing operations on arrays of different shapes under certain conditions.When operands havediffferent shapes NumPy expands the smaller array to match the larger one in a specific way to perform element-wise operations.

Practical Questions:

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [3]:
import numpy as np
x=np.random.randint(1,100,(3,3))
print(x)
y=x[::-1, ::-1]
print(y)

[[95  2 54]
 [56 52 57]
 [39 50 44]]
[[44 50 39]
 [57 52 56]
 [54  2 95]]



2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [4]:
import numpy as np
list=np.arange(1,11)
print(list)
x=list.reshape(2,5)
print(x)
y=list.reshape(5,2)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [5]:
import numpy as np
x=np.random.rand(4,4)
print(x)
y=np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0.4263849  0.22071988 0.26896207 0.06657161]
 [0.89304677 0.43048657 0.96171447 0.04035569]
 [0.3856317  0.65988935 0.95546474 0.44735411]
 [0.13113673 0.05742021 0.69323311 0.62175993]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.4263849  0.22071988 0.26896207 0.06657161 0.        ]
 [0.         0.89304677 0.43048657 0.96171447 0.04035569 0.        ]
 [0.         0.3856317  0.65988935 0.95546474 0.44735411 0.        ]
 [0.         0.13113673 0.05742021 0.69323311 0.62175993 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [6]:
import numpy as np
x=np.arange(10,60,5)
print(x)

[10 15 20 25 30 35 40 45 50 55]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [8]:
import numpy as np
x=np.array(['python', 'numpy', 'pandas'])
print(x)
y=np.char.upper(x)
print(y)
z=np.char.lower(x)
print(z)
a=np.char.title(x)
print(a)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [9]:
import numpy as np
x=np.array(['insert', 'numpy', 'array'])
print(x)
y=np.char.join(' ', x)
print(y)

['insert' 'numpy' 'array']
['i n s e r t' 'n u m p y' 'a r r a y']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [10]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
y=np.array([[7,8,9],[10,11,12]])
print(y)
z=x+y
print(z)
a=x-y
print(a)
b=x*y
print(b)
c=x/y
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [25]:
import numpy as np
x=np.ones((5,5))
x=np.identity(5)
print(x)
y=np.diag(x)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [26]:
import numpy as np
x=np.random.randint(0,1000,100)
print(x)

[892 654 700 192 119  32 240 664 311 132 369 378 178  84 213 678 906 369
 918 810 576 812  70 173 483 334  52 273 919 676 887 233  58 329 842 760
 339 228 929 663 758 401 798 592 497 579 426 349 935 471 825 156 621 562
 976 868 275 910 188 477 469 112 280 208 658 484 187 424 649 509  30 201
 564 661 265 481  67 867 119 717 391 202 532 718 670 877 253 398  74 729
 630 499 914 745 551 788 920   0 278 673]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [29]:
import numpy as np
import sys
import numpy.ma as map
from datetime import datetime as dt

